"""Gramma — chat & design history (persisted records for the Mini-App).

`ChatHistory`  → every inbound message the bot/automation touches (DM /
                 comment / story reply), so users can browse, search and
                 purge conversations (stage 2).
`DesignHistory`→ every caption / idea generated by the AI engines (OpenClaw /
                 AvalAI) so users can copy, reuse and filter designs (stage 4).

Both are purely additive tables — existing flows never depend on them.
"""

from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import BigInteger, DateTime, Index, String, Text, UniqueConstraint
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base, BIGINT_PK


class ChatHistory(Base):
    """One inbound message handled by the bot (or its automation)."""

    __tablename__ = "chat_history"
    __table_args__ = (Index("ix_chat_history_owner_channel_created", "account_id", "channel", "created_at"),)

    id: Mapped[int] = mapped_column(BIGINT_PK, primary_key=True, autoincrement=True)
    account_id: Mapped[int] = mapped_column(BigInteger, index=True)
    channel: Mapped[str] = mapped_column(String(16), default="dm")  # dm|comment|story_reply
    peer_id: Mapped[str] = mapped_column(String(128), default="")
    peer_name: Mapped[str] = mapped_column(String(255), default="")
    inbound_text: Mapped[str] = mapped_column(Text, default="")
    reply_text: Mapped[str] = mapped_column(Text, default="")
    reply_source: Mapped[str] = mapped_column(String(24), default="manual")  # manual|keyword|scenario|ai
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))


class DesignHistory(Base):
    """One AI-generated caption / post idea, kept for copy + reuse."""

    __tablename__ = "design_history"
    __table_args__ = (Index("ix_design_history_owner_created", "account_id", "created_at"),)

    id: Mapped[int] = mapped_column(BIGINT_PK, primary_key=True, autoincrement=True)
    account_id: Mapped[int] = mapped_column(BigInteger, nullable=True, index=True)  # None = not page-scoped
    kind: Mapped[str] = mapped_column(String(24), default="caption")  # caption|idea|comment_reply|dm_reply|analytics
    prompt: Mapped[str] = mapped_column(Text, default="")
    content: Mapped[str] = mapped_column(Text, default="")
    engine: Mapped[str] = mapped_column(String(24), default="openclaw")  # openclaw|avalai|template
    language: Mapped[str] = mapped_column(String(8), default="fa")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))


async def record_chat(
    session: AsyncSession,
    *,
    account_id: int,
    channel: str,
    peer_id: str,
    peer_name: str = "",
    inbound_text: str,
    reply_text: str = "",
    reply_source: str = "manual",
) -> ChatHistory:
    row = ChatHistory(
        account_id=account_id,
        channel=channel,
        peer_id=peer_id,
        peer_name=peer_name,
        inbound_text=(inbound_text or "")[:4000],
        reply_text=(reply_text or "")[:4000],
        reply_source=reply_source,
    )
    session.add(row)
    return row


async def record_design(
    session: AsyncSession,
    *,
    account_id: int | None,
    kind: str,
    prompt: str,
    content: str,
    engine: str = "openclaw",
    language: str = "fa",
) -> DesignHistory:
    row = DesignHistory(
        account_id=account_id,
        kind=kind,
        prompt=(prompt or "")[:2000],
        content=(content or "")[:8000],
        engine=engine,
        language=language,
    )
    session.add(row)
    return row


class PostReminder(Base):
    """A reminder spawned for a scheduled post (bot, Mini-App or pg_cron).

    The scheduler sends `<post_reminder_minutes_before>` minutes before a
    scheduled publish; this table records every fired reminder so it is never
    delivered twice by two different workers (serverless + local fallback).
    """

    __tablename__ = "post_reminders"
    __table_args__ = (
        UniqueConstraint("post_id", name="uq_post_reminder_post"),
        Index("ix_post_reminders_due", "remind_at", "sent_at"),
    )

    id: Mapped[int] = mapped_column(BIGINT_PK, primary_key=True, autoincrement=True)
    post_id: Mapped[int] = mapped_column(BigInteger, index=True)
    owner_id: Mapped[int] = mapped_column(BigInteger, index=True)
    remind_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), index=True)
    sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    message: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
