"""Gramma — Supabase schema DDL + provisioning helpers (serverless primary DB).

What lives here:

  * :func:`build_ddl_sql` — compile every SQLAlchemy model into PostgreSQL DDL
    suitable for Supabase:

      - ``users.id`` stays **BIGINT** (it stores the Telegram user id, not a
        serial); ``instagram_accounts`` and every other table keep a proper
        ``BIGINT GENERATED ALWAYS AS IDENTITY`` sequence so the ORM's
        ``autoincrement`` primary keys work exactly as they do on SQLite.
      - The circular FK between ``users.active_account_id`` and
        ``instagram_accounts.owner_id`` (an unresolvable recursion for plain
        ``CREATE TABLE``) is split: the ``users → instagram_accounts`` edge is
        dropped and re-added afterwards with ``ALTER TABLE``.
      - An ``updated_at`` trigger function keeps the ORM's ``updated_at``
        convention honest even for writes made from SQL (pg_cron).

  * :func:`apply_schema` — ships the DDL to the Supabase database through the
    Management API run-query endpoint (the highest-privilege migration path
    available without a Supabase CLI), idempotently (skips objects that exist).

  * :func:`run_sql` — run arbitrary SQL statements against the same endpoint
    (used by the provisioning script for RLS + pg_cron).

Nothing here ever holds credentials: the Management PAT is read from the
``SUPABASE_MANAGEMENT_TOKEN`` environment variable at call time only.
"""

from __future__ import annotations

import os
from typing import Iterable

from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

# Tables whose "BIGINT identity" primary key we must NOT auto-generate.
_MANUAL_PK_TABLES = {"users"}

_UPDATED_AT_FN = """
CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

_UPDATED_AT_TRIGGERS = [
    ("instagram_accounts", "updated_at"),
]


def _compiled_tables():
    """Compile all registered models to (tablename, create_ddl, index_ddls)."""
    from app.core.database import Base

    import app.models  # noqa: F401  (register every model)

    dialect = postgresql.dialect()
    out = []
    for table in Base.metadata.sorted_tables:
        create = str(CreateTable(table).compile(dialect=dialect)).strip()
        indexes = [
            str(CreateIndex(idx).compile(dialect=dialect)).strip()
            for idx in table.indexes
        ]
        out.append((table.name, create, indexes))
    return out


def _fix_identity(ddl: str, tablename: str) -> str:
    """users.id must be a plain BIGINT, never BIGSERIAL/identity.

    Every *other* table keeps its BIGSERIAL / GENERATED … AS IDENTITY so the
    ORM's `autoincrement` PKs behave on Postgres exactly as on SQLite.
    """
    if tablename not in _MANUAL_PK_TABLES:
        return ddl
    return ddl.replace(
        "\tid BIGSERIAL NOT NULL,", "\tid BIGINT NOT NULL,"
    ).replace(
        "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,",
        "\tid BIGINT NOT NULL,",
    ).replace(
        "\tid BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,",
        "\tid BIGINT NOT NULL,",
    )


def build_ddl_sql() -> str:
    """Return the full, Supabase-safe init schema as one SQL script.

    Ordering strategy (avoids the ORM's cyclic-FK sort problem):

      1. Emit every ``CREATE TABLE`` **without** foreign keys (+ indexes).
      2. Emit every FK as ``ALTER TABLE … ADD CONSTRAINT …`` afterwards.
      3. Add the ``updated_at`` trigger function + triggers.
    """
    import re

    tables: list[str] = []
    fks: list[tuple[str, str, str]] = []  # (table, constraint_name, clause)
    for name, create, indexes in _compiled_tables():
        create = _fix_identity(create, name)

        # Pull every table-level FOREIGN KEY line out (re-added by ALTER).
        fk_lines = re.findall(r"^\tFOREIGN KEY\(([^)]*)\)\s+REFERENCES\s+(\w+)\s*\(([^)]*)\)([^\n]*)", create, re.M)
        for cols, ref_table, ref_cols, suffix in fk_lines:
            cols_list = [c.strip() for c in cols.split(",")]
            col_key = "_".join(cols_list)
            ref_cols_list = [c.strip() for c in ref_cols.split(",")]
            ref_key = "_".join(ref_cols_list)
            fks.append(
                (
                    name,
                    f"{name}_{col_key}_fkey",
                    f"FOREIGN KEY({cols}) REFERENCES {ref_table} ({ref_cols}){suffix}",
                )
            )
        create = re.sub(r"^\tFOREIGN KEY\([^\n]*\n", "", create, flags=re.M)
        create = create.replace(", \n)", "\n)")
        tables.append(create + ";")
        for idx in indexes:
            tables.append(idx + ";")

    stmts: list[str] = tables
    for table, constraint, clause in fks:
        stmts.append(
            f"ALTER TABLE {table} ADD CONSTRAINT {constraint} {clause};"
        )

    stmts.append(_UPDATED_AT_FN.strip())
    for table, _col in _UPDATED_AT_TRIGGERS:
        stmts.append(
            f"DROP TRIGGER IF EXISTS trg_{table}_updated_at ON {table};\n"
            f"CREATE TRIGGER trg_{table}_updated_at BEFORE UPDATE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();"
        )
    return "\n\n".join(stmts) + "\n"


def _management_token() -> str:
    token = os.environ.get("SUPABASE_MANAGEMENT_TOKEN", "").strip()
    if not token:
        raise RuntimeError(
            "SUPABASE_MANAGEMENT_TOKEN (Supabase Personal Access Token) is not set"
        )
    return token


def _project_ref() -> str:
    ref = os.environ.get("SUPABASE_PROJECT_REF", "").strip()
    if not ref:
        raise RuntimeError("SUPABASE_PROJECT_REF is not set")
    return ref


def _split_statements(sql: str) -> list[str]:
    """Split a script on `;` while ignoring `;` inside ``$$ … $$`` bodies.

    Simple character scanner: a `;` only terminates a statement when we are
    *not* inside a dollar-quoted body.
    """
    statements: list[str] = []
    buf: list[str] = []
    in_dollar = False
    i = 0
    n = len(sql)
    while i < n:
        ch = sql[i]
        # Detect `$$` (dollar-quote open/close).
        if sql[i : i + 2] == "$$":
            in_dollar = not in_dollar
            buf.append("$$")
            i += 2
            continue
        if ch == ";" and not in_dollar:
            stmt = "".join(buf).strip()
            if stmt:
                statements.append(stmt)
            buf = []
            i += 1
            continue
        buf.append(ch)
        i += 1
    tail = "".join(buf).strip().rstrip(";").strip()
    if tail:
        statements.append(tail)
    return [s for s in statements if s]


async def run_sql(
    statements: Iterable[str],
    *,
    project_ref: str | None = None,
    token: str | None = None,
) -> list[dict]:
    """Execute raw SQL against the Supabase project via the Management API.

    Each statement is sent individually (no multi-statement transactions) so
    partial failures are easy to diagnose. Returns the JSON answers.
    """
    import httpx

    ref = project_ref or _project_ref()
    token = token or _management_token()
    url = f"https://api.supabase.com/v1/projects/{ref}/database/query"
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }
    results: list[dict] = []
    async with httpx.AsyncClient(timeout=60.0) as client:
        for stmt in statements:
            resp = await client.post(url, headers=headers, json={"query": stmt})
            if resp.status_code not in (200, 201):
                raise RuntimeError(
                    f"SQL failed ({resp.status_code}): {stmt[:120]!r} → "
                    f"{resp.text[:500]}"
                )
            try:
                results.append(resp.json() or {})
            except Exception:  # noqa: BLE001
                results.append({})
    return results


async def apply_schema(
    *,
    project_ref: str | None = None,
    token: str | None = None,
    skip_existing: bool = True,
) -> list[dict]:
    """Ship the full schema to Supabase (idempotent, never destructive).

    With ``skip_existing=True`` each statement is run individually and
    "already exists" style errors (table / index / constraint / trigger)
    are tolerated, so the script can be re-run safely at any time.
    """
    import httpx

    script = build_ddl_sql()
    statements = _split_statements(script)
    if not skip_existing:
        return await run_sql(statements, project_ref=project_ref, token=token)

    ref = project_ref or _project_ref()
    token = token or _management_token()
    url = f"https://api.supabase.com/v1/projects/{ref}/database/query"
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
    _IGNORE = ("already exists", "duplicate key", "duplicate object", "exists")

    results: list[dict] = []
    async with httpx.AsyncClient(timeout=60.0) as client:
        for stmt in statements:
            resp = await client.post(url, headers=headers, json={"query": stmt})
            if resp.status_code in (200, 201):
                try:
                    results.append(resp.json() or {})
                except Exception:  # noqa: BLE001
                    results.append({})
                continue
            text = resp.text.lower()
            if any(marker in text for marker in _IGNORE):
                results.append({"skipped": True, "stmt": stmt[:80]})
                continue
            raise RuntimeError(
                f"SQL failed ({resp.status_code}): {stmt[:120]!r} → {resp.text[:500]}"
            )
    return results


def _pg_literal(s: str) -> str:
    """Dollar-quote a SQL string so it can be embedded in EXECUTE."""
    return "$stmt$" + s.replace("$stmt$", "") + "$stmt$"


# ── Storage ───────────────────────────────────────────────────
async def ensure_storage_buckets(
    buckets: Iterable[str],
    *,
    project_ref: str | None = None,
    api_key: str | None = None,
) -> list[dict]:
    """Create public Storage buckets (Supabase Storage API).

    Uses the Supabase service_role/anon key (``api_key``) for BOTH the
    ``Authorization`` bearer and the ``apikey`` header — not the Management
    PAT. Falls back to ``SUPABASE_SERVICE_ROLE_KEY`` then ``SUPABASE_ANON_KEY``.
    """
    import httpx

    ref = project_ref or _project_ref()
    key = api_key or os.environ.get("SUPABASE_SERVICE_ROLE_KEY") or os.environ.get(
        "SUPABASE_ANON_KEY", ""
    )
    if not key:
        raise RuntimeError("no Supabase API key (set SUPABASE_SERVICE_ROLE_KEY)")

    base = f"https://{ref}.supabase.co/storage/v1/bucket"
    headers = {
        "Authorization": f"Bearer {key}",
        "apikey": key,
        "Content-Type": "application/json",
    }
    results: list[dict] = []
    async with httpx.AsyncClient(timeout=30.0) as client:
        for bucket in buckets:
            resp = await client.post(
                base, headers=headers, json={"id": bucket, "name": bucket, "public": True}
            )
            ok = resp.status_code in (200, 201) or "already exists" in resp.text.lower()
            results.append({"bucket": bucket, "status": resp.status_code, "ok": ok})
    return results
